name: PR Audit

on:
  pull_request:
    branches:
      - main
    paths:
      - configs/**/*
      - scripts/**/*

jobs:
  validate: # This job will fail and reject the PR if validation fails
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        # uses version from package.json > packageManager

      - name: Validate
        run: |
          pnpm install
          pnpm validate
